In [344]:
import numpy as np
import sklearn
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

## load training data from files
train_df = np.loadtxt('train.dat')
X_training = pd.DataFrame(train_df)

training_labels=np.loadtxt('train.labels')
Y_training=pd.DataFrame(training_labels)

# test_df = np.loadtxt('test.dat')
# X_test = pd.DataFrame(test_df)

In [345]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_training, Y_training, random_state=0)

In [346]:
X_train.shape

(15889, 48)

In [347]:
X_test.shape

(5297, 48)

In [348]:
y_train.shape

(15889, 1)

In [349]:
y_test.shape

(5297, 1)

In [350]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [351]:
from sklearn.decomposition import PCA

# Make an instance of the Model
#pca = PCA(n_components=40,svd_solver='randomized')
pca = PCA(n_components=30, svd_solver='randomized')

pca.fit(X_train)

X_train = pca.transform(X_train)
X_test = pca.transform(X_test)


In [342]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=25)
svd.fit(X_train)

X_train = svd.transform(X_train)
X_test = svd.transform(X_test)


In [219]:
from sklearn.linear_model import LogisticRegression


logreg = LogisticRegression(solver = 'newton-cg', multi_class ='multinomial')
logreg.fit(X_train, y_train)

print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))

/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of Logistic regression classifier on training set: 0.57
Accuracy of Logistic regression classifier on test set: 0.56


In [324]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier().fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.5f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.5f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00000
Accuracy of Decision Tree classifier on test set: 0.52728


In [353]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 7, algorithm='ball_tree')
knn.fit(X_train, np.ravel(y_train))
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

pred = knn.predict(X_test)

print(classification_report(y_test, pred))


Accuracy of K-NN classifier on training set: 0.76
Accuracy of K-NN classifier on test set: 0.70
             precision    recall  f1-score   support

        1.0       0.76      0.79      0.77      2567
        2.0       0.63      0.71      0.67      1903
        3.0       0.64      0.41      0.50       451
        4.0       0.64      0.43      0.52        88
        5.0       0.84      0.46      0.59        57
        6.0       0.00      0.00      0.00         4
        7.0       0.75      0.50      0.60        18
        8.0       0.57      0.30      0.39       205
       10.0       0.00      0.00      0.00         1
       11.0       0.00      0.00      0.00         3

avg / total       0.69      0.70      0.69      5297



/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [90]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

Accuracy of LDA classifier on training set: 0.56
Accuracy of LDA classifier on test set: 0.55


/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)


In [220]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.42
Accuracy of GNB classifier on test set: 0.40


/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [221]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of SVM classifier on training set: 0.54
Accuracy of SVM classifier on test set: 0.53


In [95]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[2015  509   26    5    1    0    0   11    0    0]
 [ 492 1333   49    1    1    0    1   26    0    0]
 [ 104  151  190    2    1    0    0    3    0    0]
 [  13   19   11   39    3    0    0    3    0    0]
 [   6    6    3   12   28    0    0    2    0    0]
 [   3    1    0    0    0    0    0    0    0    0]
 [   1    3    1    0    0    0   11    2    0    0]
 [  46   82    7    4    0    0    3   63    0    0]
 [   1    0    0    0    0    0    0    0    0    0]
 [   1    1    1    0    0    0    0    0    0    0]]
             precision    recall  f1-score   support

        1.0       0.75      0.78      0.77      2567
        2.0       0.63      0.70      0.67      1903
        3.0       0.66      0.42      0.51       451
        4.0       0.62      0.44      0.52        88
        5.0       0.82      0.49      0.62        57
        6.0       0.00      0.00      0.00         4
        7.0       0.73      0.61      0.67        18
        8.0       0.57      0.31      0.40  

/home/nikhileshsjsu/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
